### ISSUE TITLE
bindings: python: drop tests from sdist or rethink how they work

### ISSUE THREAD

**Issue by vfazio** [brgl/libgpiod#108]
We currently include the sources for the tests as part of the sdist.

The unfortunate reality is, testing changes is not as simple as just untar'ing the sdist and hacking away. There are dependencies outside of the sdist that are required to actually run the suite. Including those into the sdist and building them correctly is non-trivial and seems like a real edge case for development. Most contributors or users looking to support a new platform will ultimately clone the libgpiod repo completely in order to run the test suite.

So, at the moment, the tests only serve as an example of how to use the library and cannot actually be used to test changes to the bindings. However, we do have an examples/ directory which is _not_ included in the sdist that could serve this same purpose.

Another option, which may be less popular, is to reconsider how we're performing the tests.

Right now, the tests are "integrated" tests; they're testing the full stack from python bindings, to the external module, down to the responses from gpiosim which causes the inclusion of more sources, complicates the build, and requires elevated privileges for testing.

Most of the testing could maybe be performed by using `unittest.mock`: https://docs.python.org/3/library/unittest.mock.html

I have not tried swapping these out, but i have used mock (and it's wrapper) for pytest unit tests in other projects.

There may be two tiers of tests, the general public bindings that don't require elevation to test and the core code in the extension module which does. The C library itself already gets tested, but testing the external module covers a legitimate gap that deserves coverage somehow. The current testing method does cover all cases, but their (partial) inclusion in the sdist doesn't seem overly helpful.

**Comment by brgl** [comment]
I don't think we should go as far as dropping tests from the sdist. They are very much used, for instance in the [meta-python recipe](https://git.openembedded.org/meta-openembedded/tree/meta-python/recipes-devtools/python/python3-gpiod_2.2.1.bb). They allow to include the ptest bits and pieces in a yocto build and run the test-suite with `ptest-runner python3-gpiod` on whatever platform you target.

**Comment by vfazio** [comment]
Is this a common pattern in Yocto? To stitch two packages together to actually run tests for one of them? I realize you're focused on the Yocto scenario because that's your primary build and test environment so I will obviously defer to your expertise there. However, from a generic Python ecosystem perspective, there's a general expectation that if an sdist includes the test suite, that you can invoke that suite and show that a package was installed/built correctly, which is currently not possible with the current layout.

**Comment by vfazio** [comment]
obviously, dropping testing capability from Yocto is a non-starter, but i wonder if it could be reworked somehow

**Comment by vfazio** [comment]
I should take the time to draw a diagram to help even myself with what an approach would be. 

The current testing paradigm is all inclusive which is fantastic. It just has the downside of being generally unavailable for someone going to PyPi to download the sdist to build and test changes to the the python library itself. As it stands, the tests included in the sdist are purely for use by Yocto. Someone trying to hack on this on Raspberry Pi OS will have to clone the full repo, not rely on the sdist even for python only development (like adding a method or property to a class) . Maybe this approach is intentional, but it still means that for the general sdist case, the tests in the sdist are not generally useful and they should not attempt to use them or make them work. 

I think there are two tiers of tests: unit tests (as in, does this function return what i expect it to return with these inputs) and integrated tests (does this function play nice with all other pieces in the system). I think the unit tests which could be included in the sdist could leverage mock. The integrated tests would still be in the gpiod source tree but not in the sdist. Users could still test changes to the python part of the bindings with the sdist, but other changes, like to the external module, would have to be done via the integrated tests. Obviously all submitted patches have to pass both the unit tests and integrated tests. Divorcing the two also means that the the pure python stuff could largely be tested without needing additional system dependencies and without the need to be root.

If this is not something you're interested in, we can close the issue, but i figured this was the best avenue to at least start a discussion.

I think if larger distributions (Fedora, Debian, etc) try to package python3-gpiod they may run into issues if they try to perform any test suite validation, but maybe this is something best deferred to when it's actually a problem.

**Comment by brgl** [comment]
If a change to python bindings needs to pass the entire integration test stack anyway - what does it matter if the unit-tests are more available to users of sdist? They need to go through the hassle of using a custom kernel with gpio-sim enabled anyway.

I see it this way: there are two types of people who will run the tests: developers of libgpiod who will most likely have some hands-on experience with linux and low-level C libraries. After all: a change to python bindings needs to be done against the libgpiod repository anyway and running the test suite - providing the kernel has gpio-sim enabled - boils down to running `./configure --enable-tests --enable-bindings-python && make && <run tests>`.

The second type will be distro developers. The problem here is that each distro seems to be doing things differently. I personally maintain the yocto recipe and make sure the tests run and pass on current master and stable branches. For others, again: I'm sure package maintainers have the tools and knowledge at their disposal that will allow them to fetch the required bits and pieces and run the tests.

Having the tests in sdist still allows you to build and run them provided the system has libgpiosim which could be possibly be packaged into its own package/recipe (not only yocto, but on other distros as well).

**Comment by vfazio** [comment]
Sorry the the late reply.

> Having the tests in sdist still allows you to build and run them provided the system has libgpiosim which could be possibly be packaged into its own package/recipe (not only yocto, but on other distros as well).

I'm guessing people would have to patch `build_tests.py` because it assumes it's running out of the git checkout with the necessary libraries at specific locations in the tree.

Regardless, I hear what you're saying, modifications to the library need to be fully tested against the full stack, and I don't disagree. I do still think there's value in having them divided up, but I will let time be my ambassador and we can solve it if it becomes a problem.
