### ISSUE TITLE
unable to assert gpio when using gpiocli and gpio-manager. 

### ISSUE THREAD

**Issue by davisRoman** [brgl/libgpiod#120]
Hello, I'm running a yocto build with libgpiod v2.2, I'm interested in enabling the gpio-manager and gpiocli in order to test out gpio persistence.

Once I boot up, I see that the gpio-manager has started up properly:
![image](https://github.com/user-attachments/assets/f0f6be2b-26d7-4b7a-893d-4857a361d678)

Then I attempt to request my desired gpio which works as expected: 
![image](https://github.com/user-attachments/assets/cfbdb972-0c77-45a4-972c-0f52c6a78ab1)

However when I attempt to assert the gpio, I get the following:
![image](https://github.com/user-attachments/assets/352b50c4-7ada-44d9-9b1b-56e35b3b1146)

and journalctl also shows some additional errors:
![image](https://github.com/user-attachments/assets/177000de-983a-42ae-8d9b-c332ccadf86f)

I found this policy file that was included in libgpiod
![image](https://github.com/user-attachments/assets/2f62757e-5812-4803-ba53-60f6c731897d)

It says that root users can do anything and since I'm indeed running as root I'm not quite sure why I'm getting an error.

Any suggestions?

**Comment by brgl** [comment]
Hey! Thanks for trying it out!

Just a couple github hints: please don't post images of code, copy the actual console output and put it in code blocks. I edited the second comment for you and put the `gpio-manager` output in codeblocks.

You seem to have requested the line "as-is". Is it possible its direction is still `input`? If so, request it explicitly as output or change its direction with `gpiocli reconfigure` and try again.

**Comment by davisRoman** [comment]
Hi Bartosz,

Your suggestion did the trick! 

I just had to add `--output` when invoking `gpiocli request`.

`gpiocli` and `gpio-manager` now work as advertised! 

Thank you for introducing this much needed feature.
