### ISSUE TITLE
After "gpiomon: use the simple event loop" gpiomon exits after a few seconds

### ISSUE THREAD

**Issue by macemoneta** [brgl/libgpiod#21]
gpiomon is no longer waiting until state change on the line; it exits with RC=0 after a few seconds as if the event has triggered, with no output.

Using:
gpiomon --rising-edge --num-events=1 gpiochip0 230

**Comment by brgl** [comment]
Hi @macemoneta, thanks for catching that! Now fixed in git. I'm currently in the process of reworking the API for 1.0 release and bugs pop up pretty often in master.

**Comment by macemoneta** [comment]
Confirmed fix; thanks!
