### ISSUE TITLE
Python binding issues when importing gpiod

### ISSUE THREAD

**Issue by lucalenardi** [brgl/libgpiod#44]
Hello!

Thanks for the nice work.

We are trying to install libgpiod with its **Python bindings** on a _Beagle Bone Black – a ARMv7 32 bit SBC_. The distribution is a Debian Stretch 9.9, Kernel version is 4.14.93-bone-rt-r17.

Installed Python versions are 3.5 and 3.6.

We tried to compile and run the lib for both the system Python (3.5) and in a virtualenv with Python3.6. 

 `./autogen.sh --enable-tools=yes --prefix=<install path> --enable-bindings-python CFLAGS="-fPIC"
`
`make`
`make install`
`ldconfig`

Everything looks fine, configuration doesn't report any issue and also building stages. But as soon as we load a Python REPL and `import gpiod` we get the following exception:

`ImportError: /usr/local/lib/python3.5/dist-packages/gpiod.so: unexpected reloc type 0x03`

Anyone gets the same problem? Do you have any clue why it happens? Any suggestion?

**Comment by brgl** [comment]
I guess your python interpreter is not built with `CFLAGS=-fPIC`
