### ISSUE TITLE
Python for LineSettings has invalid __repr__

### ISSUE THREAD

**Issue by Robtom5** [brgl/libgpiod#51]
The code for __repr__ of LineSettings is missing commas to separate the arguments

Current
`LineSettings(direction={}, edge_detection={} bias={} drive={} active_low={} debounce_period={} event_clock={} output_value={})`

Correct:
`LineSettings(direction={}, edge_detection={}, bias={}, drive={}, active_low={}, debounce_period={}, event_clock={}, output_value={})`

A suitable test would be 
```python3

test_settings = LineSettings(....)
assert test_settings == eval(test_settings.__repr__())
```

**Comment by Robtom5** [comment]
username (with an underscore between the letters and number) at mac.com

**Comment by brgl** [comment]
Fix is now in master.
