### ISSUE TITLE
Error with GPIOD_LINE_REQUEST_FLAG

### ISSUE THREAD

**Issue by paulcrawford** [brgl/libgpiod#55]
I implementing gpiod for a 1wire bus on an Odroid N2L. The bus has a pull-up resistor so I added the flag for that to the line request:

`gpiod_line_request_output_flags(gpioline,"DS18B20",GPIOD_LINE_REQUEST_FLAG_OPEN_DRAIN|GPIOD_LINE_REQUEST_FLAG_BIAS_PULL_UP,1);`

The code failed with errno 22. Removing the flag prevented the error and the code works flawlessly. So it seems that it is a bug.

**Comment by brgl** [comment]
Is it a hard-wired pull-up or is this an internal one configurable by your GPIO controller?

**Comment by paulcrawford** [comment]
The pull-up resistor is hard-wired.
