### ISSUE TITLE
help for gpiomon -p doesn't mention default unit of ms or that unit suffixes are allowed

### ISSUE THREAD

**Issue by bkerin** [brgl/libgpiod#66]
I had to test then peek at source to confirm that ms was the default (and then found out that suffixes are allowed).  It might be worth mentioning default ms at least in --help output

lovely lib/tools in general btw

**Comment by warthog618** [comment]
Read the help to the bottom:

```
Periods:
    Periods are taken as milliseconds unless units are specified. e.g. 10us.
    Supported units are 's', 'ms', and 'us'.
```
