### ISSUE TITLE
gpiod_line_request_release --> application hangs

### ISSUE THREAD

**Issue by rsm47-aut** [brgl/libgpiod#67]
Hi,

I followed the example `toggle_line_value.c`.  
Basically, the example works, but it must be mentioned that the method `gpiod_line_request_release()` is never called, because the application can only be exited by Ctrl+C.

My own application, based on the example, crashes, as soon as I call `gpiod_line_request_release()`. I just want to toggle a power supply pin at the beginning and want to do some further stuff afterwards. 
Can someone review or adapt the mentioned example, so that also the `gpiod_line_request_release()` is called?
That would be great!

**Comment by brgl** [comment]
I need more info on *why* it crashes. Would you mind sharing a gdb stack trace?

**Comment by warthog618** [comment]
Updating `toggle_line_value.c` such that the for loop exits after a number of cycles works fine for me:

```
	int i;
	for (i = 0; i < 5; i++) {
...
```

Have you tried anything similar yourself?  Please provide example code that is failing for you.

**Comment by rsm47-aut** [comment]
Sorry,
I found the issue - caused by myself. Everything is fine with `gpiod_line_request_release()`.  
Sorry for that!
