### ISSUE TITLE
Remaining musl compatibility issue

### ISSUE THREAD

**Issue by tpetazzoni** [brgl/libgpiod#7]
My pull request at https://github.com/brgl/libgpiod/pull/6 contains two musl compatibility fixes. However, even with those fixes, one issue remains: src/lib/core.c uses the GNU variant of strerror_r(), while musl only provides the XSI variant of the function. This causes only a warning at compile time, but will cause a real issue at runtime, since the code is casting the "int" result of musl strerror_r() into a "char *".

**Comment by brgl** [comment]
#8

**Comment by brgl** [comment]
Patch posted for review. #9

**Comment by brgl** [comment]
Fix merged.
