### ISSUE TITLE
Tag downloads from git.kernel.org seam broken

### ISSUE THREAD

**Issue by ashley-b** [brgl/libgpiod#71]
Apologies if this is the wrong place for this issue, but when I try to download a tagged version of this project from git.kernel.org I get `404 Not Found`

eg
https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/snapshot/libgpiod-2.1.1.tar.gz
`404 Not Found`

This happens with all version https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/refs/tags

**Comment by brgl** [comment]
Must have been either a temporary outage or something in your network - it works just fine for me now.

**Comment by ashley-b** [comment]
Still seams to down. 
Thank you for the alternative URL, I will switch to that
