### ISSUE TITLE
Persistent state

### ISSUE THREAD

**Issue by dakejahl** [brgl/libgpiod#77]
> A common complaint from users about gpioset is that the state of a line is not
retained once the program exits. While this is precisely the way linux
character devices work, it's understandable that most users will want some
centralized way of controlling GPIOs - similar to how sysfs worked

Oof. This is going to break literally everyones code...

**Comment by dakejahl** [comment]
oh thank god :sweat_smile: 
https://github.com/brgl/libgpiod-private/compare/master...topic/dbus

**Comment by brgl** [comment]
I think you'll need to be more precise here because I have no idea what you're trying to report here.
