### ISSUE TITLE
--hold-period doesn't work

### ISSUE THREAD

**Issue by o-alquimista** [brgl/libgpiod#79]
After 10 seconds, the line is still busy and the "gpioset" process is still running.
```
# gpioset -c 0 --hold-period 10s GPIO18=1
```

From another terminal (after 10s), I still can't interact with the line:

```
# gpioset -c 0 GPIO18=0
gpioset: unable to request lines on chip '/dev/gpiochip0': Resource busy
```

I'm using GPIO 18 to control the official case fan for the Raspberry Pi.

### System info
- arm64 platform, Raspberry Pi 4B
- OS: Alpine Linux arm64
- libgpiod tag 2.1.2, built from source (git).

**Comment by brgl** [comment]
Actually it works as expected - it's the minimum hold period for the line. If you want the program to exit after that hold period just run: `gpioset -c 0 --hold-period 10s --toggle=0 GPIO18=1`
