### ISSUE TITLE
Please add support for ASRock IMB-1313 motherboard

### ISSUE THREAD

**Issue by is-eouellette** [brgl/libgpiod#90]
Hi,
On our ASRock IMB-1313 industrial motherboard, we're using GPIO70-GPIO72:
(Please see attached user's manual, p. 24)
GPIO70: push button switch input: N.O. (L), pushed (H)
GPIO71: buffered Green LED output: L (off), H (on)
GPIO72: buffered Amber LED output: L (off), H (on)

We're running Ubuntu 22.04 OS (tried desktop and server versions)

For gpiod, we compiled v2.2 from source code here:
https://github.com/brgl/libgpiod/tree/master

Then tried command line tools like:

sudo /usr/local/bin/gpioset --interactive -c 0 71=inactive 72=inactive
gpioset> set 71=active
gpioset> set 71=inactive
gpioset> set 71=active
gpioset> get 71
"71"=active

But I observed no changes to the LED.
Would you please help us with GPIO support for this Intel motherboard?
Thanks!
[IMB-1313 User Manual.pdf](https://github.com/user-attachments/files/16663360/IMB-1313.User.Manual.pdf)
[IMB-1313.pdf](https://github.com/user-attachments/files/16663366/IMB-1313.pdf)

**Comment by brgl** [comment]
I'm afraid you may be confused as to what libgpiod actually is. There's no support for any specific piece of HW in the library. That happens in the linux kernel which - through a well-known interface - exports the GPIO functionality to user-space. This project just wraps that kernel interface and aims at making it easier to use. You need to find out why the kernel doesn't toggle your GPIOs.
