### ISSUE TITLE
Question : gpiod_line_find() equivalent in V2.0 ?

### ISSUE THREAD

**Issue by Orel-B** [brgl/libgpiod#99]
Hello,

I am working on migrating some software using libgpiod v1.6 to V2.0.
I noticed that some useful functions are not developed in V2 such as gpiod_line_find().

I checked on V2 sources how gpioget is working with --by-name and also in : [find_line_by_name.c](https://github.com/brgl/libgpiod/blob/master/examples/find_line_by_name.c)

Why there is no function equivalent to gpiod_line_find() ?
Is an equivalent function planned to be deployed in V2 ?

Thank you,

regards

**Comment by brgl** [comment]
Because libgpiod v2 was designed to be minimal and only cover the functionality exposed by the kernel uAPI.

**Comment by Orel-B** [comment]
i understand the point, thank you for the answer :)
